/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppTasksIndexRouteImport } from './routes/_app.tasks.index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app.settings.index'
import { Route as AppReportsIndexRouteImport } from './routes/_app.reports.index'
import { Route as AppRecruitmentIndexRouteImport } from './routes/_app.recruitment.index'
import { Route as AppProjectsIndexRouteImport } from './routes/_app.projects.index'
import { Route as AppMarketingIndexRouteImport } from './routes/_app.marketing.index'
import { Route as AppKnowledgeBaseIndexRouteImport } from './routes/_app.knowledge-base.index'
import { Route as AppInventoryIndexRouteImport } from './routes/_app.inventory.index'
import { Route as AppHrmsIndexRouteImport } from './routes/_app.hrms.index'
import { Route as AppFinanceIndexRouteImport } from './routes/_app.finance.index'
import { Route as AppCrmIndexRouteImport } from './routes/_app.crm.index'
import { Route as AppCollaborationIndexRouteImport } from './routes/_app.collaboration.index'
import { Route as AppAutomationIndexRouteImport } from './routes/_app.automation.index'
import { Route as AppAiAssistantIndexRouteImport } from './routes/_app.ai-assistant.index'
import { Route as AppAccountingIndexRouteImport } from './routes/_app.accounting.index'
import { Route as AppTasksTimelineRouteImport } from './routes/_app.tasks.timeline'
import { Route as AppTasksListRouteImport } from './routes/_app.tasks.list'
import { Route as AppTasksKanbanRouteImport } from './routes/_app.tasks.kanban'
import { Route as AppTasksCalendarRouteImport } from './routes/_app.tasks.calendar'
import { Route as AppSettingsTeamRouteImport } from './routes/_app.settings.team'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app.settings.notifications'
import { Route as AppSettingsIntegrationsRouteImport } from './routes/_app.settings.integrations'
import { Route as AppSettingsBillingRouteImport } from './routes/_app.settings.billing'
import { Route as AppReportsExportsRouteImport } from './routes/_app.reports.exports'
import { Route as AppReportsAnalyticsRouteImport } from './routes/_app.reports.analytics'
import { Route as AppRecruitmentSettingsRouteImport } from './routes/_app.recruitment.settings'
import { Route as AppRecruitmentRequisitionsRouteImport } from './routes/_app.recruitment.requisitions'
import { Route as AppRecruitmentReportsRouteImport } from './routes/_app.recruitment.reports'
import { Route as AppRecruitmentOnboardingRouteImport } from './routes/_app.recruitment.onboarding'
import { Route as AppRecruitmentOffersRouteImport } from './routes/_app.recruitment.offers'
import { Route as AppRecruitmentJobsRouteImport } from './routes/_app.recruitment.jobs'
import { Route as AppRecruitmentInterviewsRouteImport } from './routes/_app.recruitment.interviews'
import { Route as AppRecruitmentCandidatesRouteImport } from './routes/_app.recruitment.candidates'
import { Route as AppRecruitmentAssessmentsRouteImport } from './routes/_app.recruitment.assessments'
import { Route as AppProjectsMilestonesRouteImport } from './routes/_app.projects.milestones'
import { Route as AppProjectsListRouteImport } from './routes/_app.projects.list'
import { Route as AppProjectsKanbanRouteImport } from './routes/_app.projects.kanban'
import { Route as AppProjectsGanttRouteImport } from './routes/_app.projects.gantt'
import { Route as AppMarketingSocialRouteImport } from './routes/_app.marketing.social'
import { Route as AppMarketingFunnelsRouteImport } from './routes/_app.marketing.funnels'
import { Route as AppMarketingEmailRouteImport } from './routes/_app.marketing.email'
import { Route as AppMarketingCampaignsRouteImport } from './routes/_app.marketing.campaigns'
import { Route as AppMarketingAutomationRouteImport } from './routes/_app.marketing.automation'
import { Route as AppMarketingAudienceRouteImport } from './routes/_app.marketing.audience'
import { Route as AppMarketingAnalyticsRouteImport } from './routes/_app.marketing.analytics'
import { Route as AppKnowledgeBaseCategoriesRouteImport } from './routes/_app.knowledge-base.categories'
import { Route as AppKnowledgeBaseArticlesRouteImport } from './routes/_app.knowledge-base.articles'
import { Route as AppInventoryWarehousesRouteImport } from './routes/_app.inventory.warehouses'
import { Route as AppInventoryVendorsRouteImport } from './routes/_app.inventory.vendors'
import { Route as AppInventoryStockRouteImport } from './routes/_app.inventory.stock'
import { Route as AppInventoryReportsRouteImport } from './routes/_app.inventory.reports'
import { Route as AppInventoryPurchaseOrdersRouteImport } from './routes/_app.inventory.purchase-orders'
import { Route as AppInventoryProductsRouteImport } from './routes/_app.inventory.products'
import { Route as AppInventoryCategoriesRouteImport } from './routes/_app.inventory.categories'
import { Route as AppInventoryAssignmentsRouteImport } from './routes/_app.inventory.assignments'
import { Route as AppInventoryAssetsRouteImport } from './routes/_app.inventory.assets'
import { Route as AppHrmsSettingsRouteImport } from './routes/_app.hrms.settings'
import { Route as AppHrmsReportsRouteImport } from './routes/_app.hrms.reports'
import { Route as AppHrmsPerformanceRouteImport } from './routes/_app.hrms.performance'
import { Route as AppHrmsPayrollRouteImport } from './routes/_app.hrms.payroll'
import { Route as AppHrmsLeaveRouteImport } from './routes/_app.hrms.leave'
import { Route as AppHrmsEmployeesRouteImport } from './routes/_app.hrms.employees'
import { Route as AppHrmsDocumentsRouteImport } from './routes/_app.hrms.documents'
import { Route as AppHrmsDepartmentsRouteImport } from './routes/_app.hrms.departments'
import { Route as AppHrmsAttendanceRouteImport } from './routes/_app.hrms.attendance'
import { Route as AppFinanceTransactionsRouteImport } from './routes/_app.finance.transactions'
import { Route as AppFinanceRevenueRouteImport } from './routes/_app.finance.revenue'
import { Route as AppFinancePaymentsRouteImport } from './routes/_app.finance.payments'
import { Route as AppFinanceInvoicesRouteImport } from './routes/_app.finance.invoices'
import { Route as AppFinanceExpensesRouteImport } from './routes/_app.finance.expenses'
import { Route as AppFinanceCashFlowRouteImport } from './routes/_app.finance.cash-flow'
import { Route as AppFinanceBudgetsRouteImport } from './routes/_app.finance.budgets'
import { Route as AppCrmSettingsRouteImport } from './routes/_app.crm.settings'
import { Route as AppCrmPipelineRouteImport } from './routes/_app.crm.pipeline'
import { Route as AppCrmLeadsRouteImport } from './routes/_app.crm.leads'
import { Route as AppCrmInboxRouteImport } from './routes/_app.crm.inbox'
import { Route as AppCrmEmailRouteImport } from './routes/_app.crm.email'
import { Route as AppCrmDealsRouteImport } from './routes/_app.crm.deals'
import { Route as AppCrmCustomersRouteImport } from './routes/_app.crm.customers'
import { Route as AppCrmCallsRouteImport } from './routes/_app.crm.calls'
import { Route as AppCrmActivitiesRouteImport } from './routes/_app.crm.activities'
import { Route as AppCollaborationMessagesRouteImport } from './routes/_app.collaboration.messages'
import { Route as AppCollaborationMeetingsRouteImport } from './routes/_app.collaboration.meetings'
import { Route as AppCollaborationChannelsRouteImport } from './routes/_app.collaboration.channels'
import { Route as AppCollaborationCallsRouteImport } from './routes/_app.collaboration.calls'
import { Route as AppAutomationWorkflowsRouteImport } from './routes/_app.automation.workflows'
import { Route as AppAutomationTriggersRouteImport } from './routes/_app.automation.triggers'
import { Route as AppAutomationLogsRouteImport } from './routes/_app.automation.logs'
import { Route as AppAiAssistantHistoryRouteImport } from './routes/_app.ai-assistant.history'
import { Route as AppAccountingTaxRouteImport } from './routes/_app.accounting.tax'
import { Route as AppAccountingReportsRouteImport } from './routes/_app.accounting.reports'
import { Route as AppAccountingLedgerRouteImport } from './routes/_app.accounting.ledger'
import { Route as AppAccountingJournalsRouteImport } from './routes/_app.accounting.journals'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksIndexRoute = AppTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsIndexRoute = AppReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitmentIndexRoute = AppRecruitmentIndexRouteImport.update({
  id: '/recruitment/',
  path: '/recruitment/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingIndexRoute = AppMarketingIndexRouteImport.update({
  id: '/marketing/',
  path: '/marketing/',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeBaseIndexRoute = AppKnowledgeBaseIndexRouteImport.update({
  id: '/knowledge-base/',
  path: '/knowledge-base/',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryIndexRoute = AppInventoryIndexRouteImport.update({
  id: '/inventory/',
  path: '/inventory/',
  getParentRoute: () => AppRoute,
} as any)
const AppHrmsIndexRoute = AppHrmsIndexRouteImport.update({
  id: '/hrms/',
  path: '/hrms/',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceIndexRoute = AppFinanceIndexRouteImport.update({
  id: '/finance/',
  path: '/finance/',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmIndexRoute = AppCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AppRoute,
} as any)
const AppCollaborationIndexRoute = AppCollaborationIndexRouteImport.update({
  id: '/collaboration/',
  path: '/collaboration/',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationIndexRoute = AppAutomationIndexRouteImport.update({
  id: '/automation/',
  path: '/automation/',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAssistantIndexRoute = AppAiAssistantIndexRouteImport.update({
  id: '/ai-assistant/',
  path: '/ai-assistant/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingIndexRoute = AppAccountingIndexRouteImport.update({
  id: '/accounting/',
  path: '/accounting/',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksTimelineRoute = AppTasksTimelineRouteImport.update({
  id: '/tasks/timeline',
  path: '/tasks/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksListRoute = AppTasksListRouteImport.update({
  id: '/tasks/list',
  path: '/tasks/list',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksKanbanRoute = AppTasksKanbanRouteImport.update({
  id: '/tasks/kanban',
  path: '/tasks/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksCalendarRoute = AppTasksCalendarRouteImport.update({
  id: '/tasks/calendar',
  path: '/tasks/calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsIntegrationsRoute = AppSettingsIntegrationsRouteImport.update({
  id: '/settings/integrations',
  path: '/settings/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsExportsRoute = AppReportsExportsRouteImport.update({
  id: '/reports/exports',
  path: '/reports/exports',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsAnalyticsRoute = AppReportsAnalyticsRouteImport.update({
  id: '/reports/analytics',
  path: '/reports/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitmentSettingsRoute = AppRecruitmentSettingsRouteImport.update({
  id: '/recruitment/settings',
  path: '/recruitment/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitmentRequisitionsRoute =
  AppRecruitmentRequisitionsRouteImport.update({
    id: '/recruitment/requisitions',
    path: '/recruitment/requisitions',
    getParentRoute: () => AppRoute,
  } as any)
const AppRecruitmentReportsRoute = AppRecruitmentReportsRouteImport.update({
  id: '/recruitment/reports',
  path: '/recruitment/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitmentOnboardingRoute =
  AppRecruitmentOnboardingRouteImport.update({
    id: '/recruitment/onboarding',
    path: '/recruitment/onboarding',
    getParentRoute: () => AppRoute,
  } as any)
const AppRecruitmentOffersRoute = AppRecruitmentOffersRouteImport.update({
  id: '/recruitment/offers',
  path: '/recruitment/offers',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitmentJobsRoute = AppRecruitmentJobsRouteImport.update({
  id: '/recruitment/jobs',
  path: '/recruitment/jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppRecruitmentInterviewsRoute =
  AppRecruitmentInterviewsRouteImport.update({
    id: '/recruitment/interviews',
    path: '/recruitment/interviews',
    getParentRoute: () => AppRoute,
  } as any)
const AppRecruitmentCandidatesRoute =
  AppRecruitmentCandidatesRouteImport.update({
    id: '/recruitment/candidates',
    path: '/recruitment/candidates',
    getParentRoute: () => AppRoute,
  } as any)
const AppRecruitmentAssessmentsRoute =
  AppRecruitmentAssessmentsRouteImport.update({
    id: '/recruitment/assessments',
    path: '/recruitment/assessments',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsMilestonesRoute = AppProjectsMilestonesRouteImport.update({
  id: '/projects/milestones',
  path: '/projects/milestones',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsListRoute = AppProjectsListRouteImport.update({
  id: '/projects/list',
  path: '/projects/list',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsKanbanRoute = AppProjectsKanbanRouteImport.update({
  id: '/projects/kanban',
  path: '/projects/kanban',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsGanttRoute = AppProjectsGanttRouteImport.update({
  id: '/projects/gantt',
  path: '/projects/gantt',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingSocialRoute = AppMarketingSocialRouteImport.update({
  id: '/marketing/social',
  path: '/marketing/social',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingFunnelsRoute = AppMarketingFunnelsRouteImport.update({
  id: '/marketing/funnels',
  path: '/marketing/funnels',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingEmailRoute = AppMarketingEmailRouteImport.update({
  id: '/marketing/email',
  path: '/marketing/email',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingCampaignsRoute = AppMarketingCampaignsRouteImport.update({
  id: '/marketing/campaigns',
  path: '/marketing/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingAutomationRoute = AppMarketingAutomationRouteImport.update({
  id: '/marketing/automation',
  path: '/marketing/automation',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingAudienceRoute = AppMarketingAudienceRouteImport.update({
  id: '/marketing/audience',
  path: '/marketing/audience',
  getParentRoute: () => AppRoute,
} as any)
const AppMarketingAnalyticsRoute = AppMarketingAnalyticsRouteImport.update({
  id: '/marketing/analytics',
  path: '/marketing/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppKnowledgeBaseCategoriesRoute =
  AppKnowledgeBaseCategoriesRouteImport.update({
    id: '/knowledge-base/categories',
    path: '/knowledge-base/categories',
    getParentRoute: () => AppRoute,
  } as any)
const AppKnowledgeBaseArticlesRoute =
  AppKnowledgeBaseArticlesRouteImport.update({
    id: '/knowledge-base/articles',
    path: '/knowledge-base/articles',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventoryWarehousesRoute = AppInventoryWarehousesRouteImport.update({
  id: '/inventory/warehouses',
  path: '/inventory/warehouses',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryVendorsRoute = AppInventoryVendorsRouteImport.update({
  id: '/inventory/vendors',
  path: '/inventory/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryStockRoute = AppInventoryStockRouteImport.update({
  id: '/inventory/stock',
  path: '/inventory/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryReportsRoute = AppInventoryReportsRouteImport.update({
  id: '/inventory/reports',
  path: '/inventory/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryPurchaseOrdersRoute =
  AppInventoryPurchaseOrdersRouteImport.update({
    id: '/inventory/purchase-orders',
    path: '/inventory/purchase-orders',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventoryProductsRoute = AppInventoryProductsRouteImport.update({
  id: '/inventory/products',
  path: '/inventory/products',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryCategoriesRoute = AppInventoryCategoriesRouteImport.update({
  id: '/inventory/categories',
  path: '/inventory/categories',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryAssignmentsRoute = AppInventoryAssignmentsRouteImport.update({
  id: '/inventory/assignments',
  path: '/inventory/assignments',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryAssetsRoute = AppInventoryAssetsRouteImport.update({
  id: '/inventory/assets',
  path: '/inventory/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppHrmsSettingsRoute = AppHrmsSettingsRouteImport.update({
  id: '/hrms/settings',
  path: '/hrms/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppHrmsReportsRoute = AppHrmsReportsRouteImport.update({
  id: '/hrms/reports',
  path: '/hrms/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppHrmsPerformanceRoute = AppHrmsPerformanceRouteImport.update({
  id: '/hrms/performance',
  path: '/hrms/performance',
  getParentRoute: () => AppRoute,
} as any)
const AppHrmsPayrollRoute = AppHrmsPayrollRouteImport.update({
  id: '/hrms/payroll',
  path: '/hrms/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppHrmsLeaveRoute = AppHrmsLeaveRouteImport.update({
  id: '/hrms/leave',
  path: '/hrms/leave',
  getParentRoute: () => AppRoute,
} as any)
const AppHrmsEmployeesRoute = AppHrmsEmployeesRouteImport.update({
  id: '/hrms/employees',
  path: '/hrms/employees',
  getParentRoute: () => AppRoute,
} as any)
const AppHrmsDocumentsRoute = AppHrmsDocumentsRouteImport.update({
  id: '/hrms/documents',
  path: '/hrms/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppHrmsDepartmentsRoute = AppHrmsDepartmentsRouteImport.update({
  id: '/hrms/departments',
  path: '/hrms/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppHrmsAttendanceRoute = AppHrmsAttendanceRouteImport.update({
  id: '/hrms/attendance',
  path: '/hrms/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceTransactionsRoute = AppFinanceTransactionsRouteImport.update({
  id: '/finance/transactions',
  path: '/finance/transactions',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRevenueRoute = AppFinanceRevenueRouteImport.update({
  id: '/finance/revenue',
  path: '/finance/revenue',
  getParentRoute: () => AppRoute,
} as any)
const AppFinancePaymentsRoute = AppFinancePaymentsRouteImport.update({
  id: '/finance/payments',
  path: '/finance/payments',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceInvoicesRoute = AppFinanceInvoicesRouteImport.update({
  id: '/finance/invoices',
  path: '/finance/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceExpensesRoute = AppFinanceExpensesRouteImport.update({
  id: '/finance/expenses',
  path: '/finance/expenses',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceCashFlowRoute = AppFinanceCashFlowRouteImport.update({
  id: '/finance/cash-flow',
  path: '/finance/cash-flow',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceBudgetsRoute = AppFinanceBudgetsRouteImport.update({
  id: '/finance/budgets',
  path: '/finance/budgets',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmSettingsRoute = AppCrmSettingsRouteImport.update({
  id: '/crm/settings',
  path: '/crm/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmPipelineRoute = AppCrmPipelineRouteImport.update({
  id: '/crm/pipeline',
  path: '/crm/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmLeadsRoute = AppCrmLeadsRouteImport.update({
  id: '/crm/leads',
  path: '/crm/leads',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmInboxRoute = AppCrmInboxRouteImport.update({
  id: '/crm/inbox',
  path: '/crm/inbox',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmEmailRoute = AppCrmEmailRouteImport.update({
  id: '/crm/email',
  path: '/crm/email',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmDealsRoute = AppCrmDealsRouteImport.update({
  id: '/crm/deals',
  path: '/crm/deals',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmCustomersRoute = AppCrmCustomersRouteImport.update({
  id: '/crm/customers',
  path: '/crm/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmCallsRoute = AppCrmCallsRouteImport.update({
  id: '/crm/calls',
  path: '/crm/calls',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmActivitiesRoute = AppCrmActivitiesRouteImport.update({
  id: '/crm/activities',
  path: '/crm/activities',
  getParentRoute: () => AppRoute,
} as any)
const AppCollaborationMessagesRoute =
  AppCollaborationMessagesRouteImport.update({
    id: '/collaboration/messages',
    path: '/collaboration/messages',
    getParentRoute: () => AppRoute,
  } as any)
const AppCollaborationMeetingsRoute =
  AppCollaborationMeetingsRouteImport.update({
    id: '/collaboration/meetings',
    path: '/collaboration/meetings',
    getParentRoute: () => AppRoute,
  } as any)
const AppCollaborationChannelsRoute =
  AppCollaborationChannelsRouteImport.update({
    id: '/collaboration/channels',
    path: '/collaboration/channels',
    getParentRoute: () => AppRoute,
  } as any)
const AppCollaborationCallsRoute = AppCollaborationCallsRouteImport.update({
  id: '/collaboration/calls',
  path: '/collaboration/calls',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationWorkflowsRoute = AppAutomationWorkflowsRouteImport.update({
  id: '/automation/workflows',
  path: '/automation/workflows',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationTriggersRoute = AppAutomationTriggersRouteImport.update({
  id: '/automation/triggers',
  path: '/automation/triggers',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationLogsRoute = AppAutomationLogsRouteImport.update({
  id: '/automation/logs',
  path: '/automation/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAssistantHistoryRoute = AppAiAssistantHistoryRouteImport.update({
  id: '/ai-assistant/history',
  path: '/ai-assistant/history',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingTaxRoute = AppAccountingTaxRouteImport.update({
  id: '/accounting/tax',
  path: '/accounting/tax',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingReportsRoute = AppAccountingReportsRouteImport.update({
  id: '/accounting/reports',
  path: '/accounting/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingLedgerRoute = AppAccountingLedgerRouteImport.update({
  id: '/accounting/ledger',
  path: '/accounting/ledger',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountingJournalsRoute = AppAccountingJournalsRouteImport.update({
  id: '/accounting/journals',
  path: '/accounting/journals',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/accounting/journals': typeof AppAccountingJournalsRoute
  '/accounting/ledger': typeof AppAccountingLedgerRoute
  '/accounting/reports': typeof AppAccountingReportsRoute
  '/accounting/tax': typeof AppAccountingTaxRoute
  '/ai-assistant/history': typeof AppAiAssistantHistoryRoute
  '/automation/logs': typeof AppAutomationLogsRoute
  '/automation/triggers': typeof AppAutomationTriggersRoute
  '/automation/workflows': typeof AppAutomationWorkflowsRoute
  '/collaboration/calls': typeof AppCollaborationCallsRoute
  '/collaboration/channels': typeof AppCollaborationChannelsRoute
  '/collaboration/meetings': typeof AppCollaborationMeetingsRoute
  '/collaboration/messages': typeof AppCollaborationMessagesRoute
  '/crm/activities': typeof AppCrmActivitiesRoute
  '/crm/calls': typeof AppCrmCallsRoute
  '/crm/customers': typeof AppCrmCustomersRoute
  '/crm/deals': typeof AppCrmDealsRoute
  '/crm/email': typeof AppCrmEmailRoute
  '/crm/inbox': typeof AppCrmInboxRoute
  '/crm/leads': typeof AppCrmLeadsRoute
  '/crm/pipeline': typeof AppCrmPipelineRoute
  '/crm/settings': typeof AppCrmSettingsRoute
  '/finance/budgets': typeof AppFinanceBudgetsRoute
  '/finance/cash-flow': typeof AppFinanceCashFlowRoute
  '/finance/expenses': typeof AppFinanceExpensesRoute
  '/finance/invoices': typeof AppFinanceInvoicesRoute
  '/finance/payments': typeof AppFinancePaymentsRoute
  '/finance/revenue': typeof AppFinanceRevenueRoute
  '/finance/transactions': typeof AppFinanceTransactionsRoute
  '/hrms/attendance': typeof AppHrmsAttendanceRoute
  '/hrms/departments': typeof AppHrmsDepartmentsRoute
  '/hrms/documents': typeof AppHrmsDocumentsRoute
  '/hrms/employees': typeof AppHrmsEmployeesRoute
  '/hrms/leave': typeof AppHrmsLeaveRoute
  '/hrms/payroll': typeof AppHrmsPayrollRoute
  '/hrms/performance': typeof AppHrmsPerformanceRoute
  '/hrms/reports': typeof AppHrmsReportsRoute
  '/hrms/settings': typeof AppHrmsSettingsRoute
  '/inventory/assets': typeof AppInventoryAssetsRoute
  '/inventory/assignments': typeof AppInventoryAssignmentsRoute
  '/inventory/categories': typeof AppInventoryCategoriesRoute
  '/inventory/products': typeof AppInventoryProductsRoute
  '/inventory/purchase-orders': typeof AppInventoryPurchaseOrdersRoute
  '/inventory/reports': typeof AppInventoryReportsRoute
  '/inventory/stock': typeof AppInventoryStockRoute
  '/inventory/vendors': typeof AppInventoryVendorsRoute
  '/inventory/warehouses': typeof AppInventoryWarehousesRoute
  '/knowledge-base/articles': typeof AppKnowledgeBaseArticlesRoute
  '/knowledge-base/categories': typeof AppKnowledgeBaseCategoriesRoute
  '/marketing/analytics': typeof AppMarketingAnalyticsRoute
  '/marketing/audience': typeof AppMarketingAudienceRoute
  '/marketing/automation': typeof AppMarketingAutomationRoute
  '/marketing/campaigns': typeof AppMarketingCampaignsRoute
  '/marketing/email': typeof AppMarketingEmailRoute
  '/marketing/funnels': typeof AppMarketingFunnelsRoute
  '/marketing/social': typeof AppMarketingSocialRoute
  '/projects/gantt': typeof AppProjectsGanttRoute
  '/projects/kanban': typeof AppProjectsKanbanRoute
  '/projects/list': typeof AppProjectsListRoute
  '/projects/milestones': typeof AppProjectsMilestonesRoute
  '/recruitment/assessments': typeof AppRecruitmentAssessmentsRoute
  '/recruitment/candidates': typeof AppRecruitmentCandidatesRoute
  '/recruitment/interviews': typeof AppRecruitmentInterviewsRoute
  '/recruitment/jobs': typeof AppRecruitmentJobsRoute
  '/recruitment/offers': typeof AppRecruitmentOffersRoute
  '/recruitment/onboarding': typeof AppRecruitmentOnboardingRoute
  '/recruitment/reports': typeof AppRecruitmentReportsRoute
  '/recruitment/requisitions': typeof AppRecruitmentRequisitionsRoute
  '/recruitment/settings': typeof AppRecruitmentSettingsRoute
  '/reports/analytics': typeof AppReportsAnalyticsRoute
  '/reports/exports': typeof AppReportsExportsRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/tasks/calendar': typeof AppTasksCalendarRoute
  '/tasks/kanban': typeof AppTasksKanbanRoute
  '/tasks/list': typeof AppTasksListRoute
  '/tasks/timeline': typeof AppTasksTimelineRoute
  '/accounting/': typeof AppAccountingIndexRoute
  '/ai-assistant/': typeof AppAiAssistantIndexRoute
  '/automation/': typeof AppAutomationIndexRoute
  '/collaboration/': typeof AppCollaborationIndexRoute
  '/crm/': typeof AppCrmIndexRoute
  '/finance/': typeof AppFinanceIndexRoute
  '/hrms/': typeof AppHrmsIndexRoute
  '/inventory/': typeof AppInventoryIndexRoute
  '/knowledge-base/': typeof AppKnowledgeBaseIndexRoute
  '/marketing/': typeof AppMarketingIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/recruitment/': typeof AppRecruitmentIndexRoute
  '/reports/': typeof AppReportsIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/tasks/': typeof AppTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/accounting/journals': typeof AppAccountingJournalsRoute
  '/accounting/ledger': typeof AppAccountingLedgerRoute
  '/accounting/reports': typeof AppAccountingReportsRoute
  '/accounting/tax': typeof AppAccountingTaxRoute
  '/ai-assistant/history': typeof AppAiAssistantHistoryRoute
  '/automation/logs': typeof AppAutomationLogsRoute
  '/automation/triggers': typeof AppAutomationTriggersRoute
  '/automation/workflows': typeof AppAutomationWorkflowsRoute
  '/collaboration/calls': typeof AppCollaborationCallsRoute
  '/collaboration/channels': typeof AppCollaborationChannelsRoute
  '/collaboration/meetings': typeof AppCollaborationMeetingsRoute
  '/collaboration/messages': typeof AppCollaborationMessagesRoute
  '/crm/activities': typeof AppCrmActivitiesRoute
  '/crm/calls': typeof AppCrmCallsRoute
  '/crm/customers': typeof AppCrmCustomersRoute
  '/crm/deals': typeof AppCrmDealsRoute
  '/crm/email': typeof AppCrmEmailRoute
  '/crm/inbox': typeof AppCrmInboxRoute
  '/crm/leads': typeof AppCrmLeadsRoute
  '/crm/pipeline': typeof AppCrmPipelineRoute
  '/crm/settings': typeof AppCrmSettingsRoute
  '/finance/budgets': typeof AppFinanceBudgetsRoute
  '/finance/cash-flow': typeof AppFinanceCashFlowRoute
  '/finance/expenses': typeof AppFinanceExpensesRoute
  '/finance/invoices': typeof AppFinanceInvoicesRoute
  '/finance/payments': typeof AppFinancePaymentsRoute
  '/finance/revenue': typeof AppFinanceRevenueRoute
  '/finance/transactions': typeof AppFinanceTransactionsRoute
  '/hrms/attendance': typeof AppHrmsAttendanceRoute
  '/hrms/departments': typeof AppHrmsDepartmentsRoute
  '/hrms/documents': typeof AppHrmsDocumentsRoute
  '/hrms/employees': typeof AppHrmsEmployeesRoute
  '/hrms/leave': typeof AppHrmsLeaveRoute
  '/hrms/payroll': typeof AppHrmsPayrollRoute
  '/hrms/performance': typeof AppHrmsPerformanceRoute
  '/hrms/reports': typeof AppHrmsReportsRoute
  '/hrms/settings': typeof AppHrmsSettingsRoute
  '/inventory/assets': typeof AppInventoryAssetsRoute
  '/inventory/assignments': typeof AppInventoryAssignmentsRoute
  '/inventory/categories': typeof AppInventoryCategoriesRoute
  '/inventory/products': typeof AppInventoryProductsRoute
  '/inventory/purchase-orders': typeof AppInventoryPurchaseOrdersRoute
  '/inventory/reports': typeof AppInventoryReportsRoute
  '/inventory/stock': typeof AppInventoryStockRoute
  '/inventory/vendors': typeof AppInventoryVendorsRoute
  '/inventory/warehouses': typeof AppInventoryWarehousesRoute
  '/knowledge-base/articles': typeof AppKnowledgeBaseArticlesRoute
  '/knowledge-base/categories': typeof AppKnowledgeBaseCategoriesRoute
  '/marketing/analytics': typeof AppMarketingAnalyticsRoute
  '/marketing/audience': typeof AppMarketingAudienceRoute
  '/marketing/automation': typeof AppMarketingAutomationRoute
  '/marketing/campaigns': typeof AppMarketingCampaignsRoute
  '/marketing/email': typeof AppMarketingEmailRoute
  '/marketing/funnels': typeof AppMarketingFunnelsRoute
  '/marketing/social': typeof AppMarketingSocialRoute
  '/projects/gantt': typeof AppProjectsGanttRoute
  '/projects/kanban': typeof AppProjectsKanbanRoute
  '/projects/list': typeof AppProjectsListRoute
  '/projects/milestones': typeof AppProjectsMilestonesRoute
  '/recruitment/assessments': typeof AppRecruitmentAssessmentsRoute
  '/recruitment/candidates': typeof AppRecruitmentCandidatesRoute
  '/recruitment/interviews': typeof AppRecruitmentInterviewsRoute
  '/recruitment/jobs': typeof AppRecruitmentJobsRoute
  '/recruitment/offers': typeof AppRecruitmentOffersRoute
  '/recruitment/onboarding': typeof AppRecruitmentOnboardingRoute
  '/recruitment/reports': typeof AppRecruitmentReportsRoute
  '/recruitment/requisitions': typeof AppRecruitmentRequisitionsRoute
  '/recruitment/settings': typeof AppRecruitmentSettingsRoute
  '/reports/analytics': typeof AppReportsAnalyticsRoute
  '/reports/exports': typeof AppReportsExportsRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/tasks/calendar': typeof AppTasksCalendarRoute
  '/tasks/kanban': typeof AppTasksKanbanRoute
  '/tasks/list': typeof AppTasksListRoute
  '/tasks/timeline': typeof AppTasksTimelineRoute
  '/accounting': typeof AppAccountingIndexRoute
  '/ai-assistant': typeof AppAiAssistantIndexRoute
  '/automation': typeof AppAutomationIndexRoute
  '/collaboration': typeof AppCollaborationIndexRoute
  '/crm': typeof AppCrmIndexRoute
  '/finance': typeof AppFinanceIndexRoute
  '/hrms': typeof AppHrmsIndexRoute
  '/inventory': typeof AppInventoryIndexRoute
  '/knowledge-base': typeof AppKnowledgeBaseIndexRoute
  '/marketing': typeof AppMarketingIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/recruitment': typeof AppRecruitmentIndexRoute
  '/reports': typeof AppReportsIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/tasks': typeof AppTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/accounting/journals': typeof AppAccountingJournalsRoute
  '/_app/accounting/ledger': typeof AppAccountingLedgerRoute
  '/_app/accounting/reports': typeof AppAccountingReportsRoute
  '/_app/accounting/tax': typeof AppAccountingTaxRoute
  '/_app/ai-assistant/history': typeof AppAiAssistantHistoryRoute
  '/_app/automation/logs': typeof AppAutomationLogsRoute
  '/_app/automation/triggers': typeof AppAutomationTriggersRoute
  '/_app/automation/workflows': typeof AppAutomationWorkflowsRoute
  '/_app/collaboration/calls': typeof AppCollaborationCallsRoute
  '/_app/collaboration/channels': typeof AppCollaborationChannelsRoute
  '/_app/collaboration/meetings': typeof AppCollaborationMeetingsRoute
  '/_app/collaboration/messages': typeof AppCollaborationMessagesRoute
  '/_app/crm/activities': typeof AppCrmActivitiesRoute
  '/_app/crm/calls': typeof AppCrmCallsRoute
  '/_app/crm/customers': typeof AppCrmCustomersRoute
  '/_app/crm/deals': typeof AppCrmDealsRoute
  '/_app/crm/email': typeof AppCrmEmailRoute
  '/_app/crm/inbox': typeof AppCrmInboxRoute
  '/_app/crm/leads': typeof AppCrmLeadsRoute
  '/_app/crm/pipeline': typeof AppCrmPipelineRoute
  '/_app/crm/settings': typeof AppCrmSettingsRoute
  '/_app/finance/budgets': typeof AppFinanceBudgetsRoute
  '/_app/finance/cash-flow': typeof AppFinanceCashFlowRoute
  '/_app/finance/expenses': typeof AppFinanceExpensesRoute
  '/_app/finance/invoices': typeof AppFinanceInvoicesRoute
  '/_app/finance/payments': typeof AppFinancePaymentsRoute
  '/_app/finance/revenue': typeof AppFinanceRevenueRoute
  '/_app/finance/transactions': typeof AppFinanceTransactionsRoute
  '/_app/hrms/attendance': typeof AppHrmsAttendanceRoute
  '/_app/hrms/departments': typeof AppHrmsDepartmentsRoute
  '/_app/hrms/documents': typeof AppHrmsDocumentsRoute
  '/_app/hrms/employees': typeof AppHrmsEmployeesRoute
  '/_app/hrms/leave': typeof AppHrmsLeaveRoute
  '/_app/hrms/payroll': typeof AppHrmsPayrollRoute
  '/_app/hrms/performance': typeof AppHrmsPerformanceRoute
  '/_app/hrms/reports': typeof AppHrmsReportsRoute
  '/_app/hrms/settings': typeof AppHrmsSettingsRoute
  '/_app/inventory/assets': typeof AppInventoryAssetsRoute
  '/_app/inventory/assignments': typeof AppInventoryAssignmentsRoute
  '/_app/inventory/categories': typeof AppInventoryCategoriesRoute
  '/_app/inventory/products': typeof AppInventoryProductsRoute
  '/_app/inventory/purchase-orders': typeof AppInventoryPurchaseOrdersRoute
  '/_app/inventory/reports': typeof AppInventoryReportsRoute
  '/_app/inventory/stock': typeof AppInventoryStockRoute
  '/_app/inventory/vendors': typeof AppInventoryVendorsRoute
  '/_app/inventory/warehouses': typeof AppInventoryWarehousesRoute
  '/_app/knowledge-base/articles': typeof AppKnowledgeBaseArticlesRoute
  '/_app/knowledge-base/categories': typeof AppKnowledgeBaseCategoriesRoute
  '/_app/marketing/analytics': typeof AppMarketingAnalyticsRoute
  '/_app/marketing/audience': typeof AppMarketingAudienceRoute
  '/_app/marketing/automation': typeof AppMarketingAutomationRoute
  '/_app/marketing/campaigns': typeof AppMarketingCampaignsRoute
  '/_app/marketing/email': typeof AppMarketingEmailRoute
  '/_app/marketing/funnels': typeof AppMarketingFunnelsRoute
  '/_app/marketing/social': typeof AppMarketingSocialRoute
  '/_app/projects/gantt': typeof AppProjectsGanttRoute
  '/_app/projects/kanban': typeof AppProjectsKanbanRoute
  '/_app/projects/list': typeof AppProjectsListRoute
  '/_app/projects/milestones': typeof AppProjectsMilestonesRoute
  '/_app/recruitment/assessments': typeof AppRecruitmentAssessmentsRoute
  '/_app/recruitment/candidates': typeof AppRecruitmentCandidatesRoute
  '/_app/recruitment/interviews': typeof AppRecruitmentInterviewsRoute
  '/_app/recruitment/jobs': typeof AppRecruitmentJobsRoute
  '/_app/recruitment/offers': typeof AppRecruitmentOffersRoute
  '/_app/recruitment/onboarding': typeof AppRecruitmentOnboardingRoute
  '/_app/recruitment/reports': typeof AppRecruitmentReportsRoute
  '/_app/recruitment/requisitions': typeof AppRecruitmentRequisitionsRoute
  '/_app/recruitment/settings': typeof AppRecruitmentSettingsRoute
  '/_app/reports/analytics': typeof AppReportsAnalyticsRoute
  '/_app/reports/exports': typeof AppReportsExportsRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/integrations': typeof AppSettingsIntegrationsRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/team': typeof AppSettingsTeamRoute
  '/_app/tasks/calendar': typeof AppTasksCalendarRoute
  '/_app/tasks/kanban': typeof AppTasksKanbanRoute
  '/_app/tasks/list': typeof AppTasksListRoute
  '/_app/tasks/timeline': typeof AppTasksTimelineRoute
  '/_app/accounting/': typeof AppAccountingIndexRoute
  '/_app/ai-assistant/': typeof AppAiAssistantIndexRoute
  '/_app/automation/': typeof AppAutomationIndexRoute
  '/_app/collaboration/': typeof AppCollaborationIndexRoute
  '/_app/crm/': typeof AppCrmIndexRoute
  '/_app/finance/': typeof AppFinanceIndexRoute
  '/_app/hrms/': typeof AppHrmsIndexRoute
  '/_app/inventory/': typeof AppInventoryIndexRoute
  '/_app/knowledge-base/': typeof AppKnowledgeBaseIndexRoute
  '/_app/marketing/': typeof AppMarketingIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/recruitment/': typeof AppRecruitmentIndexRoute
  '/_app/reports/': typeof AppReportsIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/tasks/': typeof AppTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounting/journals'
    | '/accounting/ledger'
    | '/accounting/reports'
    | '/accounting/tax'
    | '/ai-assistant/history'
    | '/automation/logs'
    | '/automation/triggers'
    | '/automation/workflows'
    | '/collaboration/calls'
    | '/collaboration/channels'
    | '/collaboration/meetings'
    | '/collaboration/messages'
    | '/crm/activities'
    | '/crm/calls'
    | '/crm/customers'
    | '/crm/deals'
    | '/crm/email'
    | '/crm/inbox'
    | '/crm/leads'
    | '/crm/pipeline'
    | '/crm/settings'
    | '/finance/budgets'
    | '/finance/cash-flow'
    | '/finance/expenses'
    | '/finance/invoices'
    | '/finance/payments'
    | '/finance/revenue'
    | '/finance/transactions'
    | '/hrms/attendance'
    | '/hrms/departments'
    | '/hrms/documents'
    | '/hrms/employees'
    | '/hrms/leave'
    | '/hrms/payroll'
    | '/hrms/performance'
    | '/hrms/reports'
    | '/hrms/settings'
    | '/inventory/assets'
    | '/inventory/assignments'
    | '/inventory/categories'
    | '/inventory/products'
    | '/inventory/purchase-orders'
    | '/inventory/reports'
    | '/inventory/stock'
    | '/inventory/vendors'
    | '/inventory/warehouses'
    | '/knowledge-base/articles'
    | '/knowledge-base/categories'
    | '/marketing/analytics'
    | '/marketing/audience'
    | '/marketing/automation'
    | '/marketing/campaigns'
    | '/marketing/email'
    | '/marketing/funnels'
    | '/marketing/social'
    | '/projects/gantt'
    | '/projects/kanban'
    | '/projects/list'
    | '/projects/milestones'
    | '/recruitment/assessments'
    | '/recruitment/candidates'
    | '/recruitment/interviews'
    | '/recruitment/jobs'
    | '/recruitment/offers'
    | '/recruitment/onboarding'
    | '/recruitment/reports'
    | '/recruitment/requisitions'
    | '/recruitment/settings'
    | '/reports/analytics'
    | '/reports/exports'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/team'
    | '/tasks/calendar'
    | '/tasks/kanban'
    | '/tasks/list'
    | '/tasks/timeline'
    | '/accounting/'
    | '/ai-assistant/'
    | '/automation/'
    | '/collaboration/'
    | '/crm/'
    | '/finance/'
    | '/hrms/'
    | '/inventory/'
    | '/knowledge-base/'
    | '/marketing/'
    | '/projects/'
    | '/recruitment/'
    | '/reports/'
    | '/settings/'
    | '/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounting/journals'
    | '/accounting/ledger'
    | '/accounting/reports'
    | '/accounting/tax'
    | '/ai-assistant/history'
    | '/automation/logs'
    | '/automation/triggers'
    | '/automation/workflows'
    | '/collaboration/calls'
    | '/collaboration/channels'
    | '/collaboration/meetings'
    | '/collaboration/messages'
    | '/crm/activities'
    | '/crm/calls'
    | '/crm/customers'
    | '/crm/deals'
    | '/crm/email'
    | '/crm/inbox'
    | '/crm/leads'
    | '/crm/pipeline'
    | '/crm/settings'
    | '/finance/budgets'
    | '/finance/cash-flow'
    | '/finance/expenses'
    | '/finance/invoices'
    | '/finance/payments'
    | '/finance/revenue'
    | '/finance/transactions'
    | '/hrms/attendance'
    | '/hrms/departments'
    | '/hrms/documents'
    | '/hrms/employees'
    | '/hrms/leave'
    | '/hrms/payroll'
    | '/hrms/performance'
    | '/hrms/reports'
    | '/hrms/settings'
    | '/inventory/assets'
    | '/inventory/assignments'
    | '/inventory/categories'
    | '/inventory/products'
    | '/inventory/purchase-orders'
    | '/inventory/reports'
    | '/inventory/stock'
    | '/inventory/vendors'
    | '/inventory/warehouses'
    | '/knowledge-base/articles'
    | '/knowledge-base/categories'
    | '/marketing/analytics'
    | '/marketing/audience'
    | '/marketing/automation'
    | '/marketing/campaigns'
    | '/marketing/email'
    | '/marketing/funnels'
    | '/marketing/social'
    | '/projects/gantt'
    | '/projects/kanban'
    | '/projects/list'
    | '/projects/milestones'
    | '/recruitment/assessments'
    | '/recruitment/candidates'
    | '/recruitment/interviews'
    | '/recruitment/jobs'
    | '/recruitment/offers'
    | '/recruitment/onboarding'
    | '/recruitment/reports'
    | '/recruitment/requisitions'
    | '/recruitment/settings'
    | '/reports/analytics'
    | '/reports/exports'
    | '/settings/billing'
    | '/settings/integrations'
    | '/settings/notifications'
    | '/settings/team'
    | '/tasks/calendar'
    | '/tasks/kanban'
    | '/tasks/list'
    | '/tasks/timeline'
    | '/accounting'
    | '/ai-assistant'
    | '/automation'
    | '/collaboration'
    | '/crm'
    | '/finance'
    | '/hrms'
    | '/inventory'
    | '/knowledge-base'
    | '/marketing'
    | '/projects'
    | '/recruitment'
    | '/reports'
    | '/settings'
    | '/tasks'
  id:
    | '__root__'
    | '/_app'
    | '/_app/'
    | '/_app/accounting/journals'
    | '/_app/accounting/ledger'
    | '/_app/accounting/reports'
    | '/_app/accounting/tax'
    | '/_app/ai-assistant/history'
    | '/_app/automation/logs'
    | '/_app/automation/triggers'
    | '/_app/automation/workflows'
    | '/_app/collaboration/calls'
    | '/_app/collaboration/channels'
    | '/_app/collaboration/meetings'
    | '/_app/collaboration/messages'
    | '/_app/crm/activities'
    | '/_app/crm/calls'
    | '/_app/crm/customers'
    | '/_app/crm/deals'
    | '/_app/crm/email'
    | '/_app/crm/inbox'
    | '/_app/crm/leads'
    | '/_app/crm/pipeline'
    | '/_app/crm/settings'
    | '/_app/finance/budgets'
    | '/_app/finance/cash-flow'
    | '/_app/finance/expenses'
    | '/_app/finance/invoices'
    | '/_app/finance/payments'
    | '/_app/finance/revenue'
    | '/_app/finance/transactions'
    | '/_app/hrms/attendance'
    | '/_app/hrms/departments'
    | '/_app/hrms/documents'
    | '/_app/hrms/employees'
    | '/_app/hrms/leave'
    | '/_app/hrms/payroll'
    | '/_app/hrms/performance'
    | '/_app/hrms/reports'
    | '/_app/hrms/settings'
    | '/_app/inventory/assets'
    | '/_app/inventory/assignments'
    | '/_app/inventory/categories'
    | '/_app/inventory/products'
    | '/_app/inventory/purchase-orders'
    | '/_app/inventory/reports'
    | '/_app/inventory/stock'
    | '/_app/inventory/vendors'
    | '/_app/inventory/warehouses'
    | '/_app/knowledge-base/articles'
    | '/_app/knowledge-base/categories'
    | '/_app/marketing/analytics'
    | '/_app/marketing/audience'
    | '/_app/marketing/automation'
    | '/_app/marketing/campaigns'
    | '/_app/marketing/email'
    | '/_app/marketing/funnels'
    | '/_app/marketing/social'
    | '/_app/projects/gantt'
    | '/_app/projects/kanban'
    | '/_app/projects/list'
    | '/_app/projects/milestones'
    | '/_app/recruitment/assessments'
    | '/_app/recruitment/candidates'
    | '/_app/recruitment/interviews'
    | '/_app/recruitment/jobs'
    | '/_app/recruitment/offers'
    | '/_app/recruitment/onboarding'
    | '/_app/recruitment/reports'
    | '/_app/recruitment/requisitions'
    | '/_app/recruitment/settings'
    | '/_app/reports/analytics'
    | '/_app/reports/exports'
    | '/_app/settings/billing'
    | '/_app/settings/integrations'
    | '/_app/settings/notifications'
    | '/_app/settings/team'
    | '/_app/tasks/calendar'
    | '/_app/tasks/kanban'
    | '/_app/tasks/list'
    | '/_app/tasks/timeline'
    | '/_app/accounting/'
    | '/_app/ai-assistant/'
    | '/_app/automation/'
    | '/_app/collaboration/'
    | '/_app/crm/'
    | '/_app/finance/'
    | '/_app/hrms/'
    | '/_app/inventory/'
    | '/_app/knowledge-base/'
    | '/_app/marketing/'
    | '/_app/projects/'
    | '/_app/recruitment/'
    | '/_app/reports/'
    | '/_app/settings/'
    | '/_app/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/': {
      id: '/_app/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AppTasksIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/': {
      id: '/_app/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AppReportsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment/': {
      id: '/_app/recruitment/'
      path: '/recruitment'
      fullPath: '/recruitment/'
      preLoaderRoute: typeof AppRecruitmentIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing/': {
      id: '/_app/marketing/'
      path: '/marketing'
      fullPath: '/marketing/'
      preLoaderRoute: typeof AppMarketingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge-base/': {
      id: '/_app/knowledge-base/'
      path: '/knowledge-base'
      fullPath: '/knowledge-base/'
      preLoaderRoute: typeof AppKnowledgeBaseIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/': {
      id: '/_app/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AppInventoryIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hrms/': {
      id: '/_app/hrms/'
      path: '/hrms'
      fullPath: '/hrms/'
      preLoaderRoute: typeof AppHrmsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/': {
      id: '/_app/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AppFinanceIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/': {
      id: '/_app/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof AppCrmIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collaboration/': {
      id: '/_app/collaboration/'
      path: '/collaboration'
      fullPath: '/collaboration/'
      preLoaderRoute: typeof AppCollaborationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation/': {
      id: '/_app/automation/'
      path: '/automation'
      fullPath: '/automation/'
      preLoaderRoute: typeof AppAutomationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-assistant/': {
      id: '/_app/ai-assistant/'
      path: '/ai-assistant'
      fullPath: '/ai-assistant/'
      preLoaderRoute: typeof AppAiAssistantIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/': {
      id: '/_app/accounting/'
      path: '/accounting'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AppAccountingIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/timeline': {
      id: '/_app/tasks/timeline'
      path: '/tasks/timeline'
      fullPath: '/tasks/timeline'
      preLoaderRoute: typeof AppTasksTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/list': {
      id: '/_app/tasks/list'
      path: '/tasks/list'
      fullPath: '/tasks/list'
      preLoaderRoute: typeof AppTasksListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/kanban': {
      id: '/_app/tasks/kanban'
      path: '/tasks/kanban'
      fullPath: '/tasks/kanban'
      preLoaderRoute: typeof AppTasksKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks/calendar': {
      id: '/_app/tasks/calendar'
      path: '/tasks/calendar'
      fullPath: '/tasks/calendar'
      preLoaderRoute: typeof AppTasksCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/team': {
      id: '/_app/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/integrations': {
      id: '/_app/settings/integrations'
      path: '/settings/integrations'
      fullPath: '/settings/integrations'
      preLoaderRoute: typeof AppSettingsIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/exports': {
      id: '/_app/reports/exports'
      path: '/reports/exports'
      fullPath: '/reports/exports'
      preLoaderRoute: typeof AppReportsExportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/analytics': {
      id: '/_app/reports/analytics'
      path: '/reports/analytics'
      fullPath: '/reports/analytics'
      preLoaderRoute: typeof AppReportsAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment/settings': {
      id: '/_app/recruitment/settings'
      path: '/recruitment/settings'
      fullPath: '/recruitment/settings'
      preLoaderRoute: typeof AppRecruitmentSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment/requisitions': {
      id: '/_app/recruitment/requisitions'
      path: '/recruitment/requisitions'
      fullPath: '/recruitment/requisitions'
      preLoaderRoute: typeof AppRecruitmentRequisitionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment/reports': {
      id: '/_app/recruitment/reports'
      path: '/recruitment/reports'
      fullPath: '/recruitment/reports'
      preLoaderRoute: typeof AppRecruitmentReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment/onboarding': {
      id: '/_app/recruitment/onboarding'
      path: '/recruitment/onboarding'
      fullPath: '/recruitment/onboarding'
      preLoaderRoute: typeof AppRecruitmentOnboardingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment/offers': {
      id: '/_app/recruitment/offers'
      path: '/recruitment/offers'
      fullPath: '/recruitment/offers'
      preLoaderRoute: typeof AppRecruitmentOffersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment/jobs': {
      id: '/_app/recruitment/jobs'
      path: '/recruitment/jobs'
      fullPath: '/recruitment/jobs'
      preLoaderRoute: typeof AppRecruitmentJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment/interviews': {
      id: '/_app/recruitment/interviews'
      path: '/recruitment/interviews'
      fullPath: '/recruitment/interviews'
      preLoaderRoute: typeof AppRecruitmentInterviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment/candidates': {
      id: '/_app/recruitment/candidates'
      path: '/recruitment/candidates'
      fullPath: '/recruitment/candidates'
      preLoaderRoute: typeof AppRecruitmentCandidatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/recruitment/assessments': {
      id: '/_app/recruitment/assessments'
      path: '/recruitment/assessments'
      fullPath: '/recruitment/assessments'
      preLoaderRoute: typeof AppRecruitmentAssessmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/milestones': {
      id: '/_app/projects/milestones'
      path: '/projects/milestones'
      fullPath: '/projects/milestones'
      preLoaderRoute: typeof AppProjectsMilestonesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/list': {
      id: '/_app/projects/list'
      path: '/projects/list'
      fullPath: '/projects/list'
      preLoaderRoute: typeof AppProjectsListRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/kanban': {
      id: '/_app/projects/kanban'
      path: '/projects/kanban'
      fullPath: '/projects/kanban'
      preLoaderRoute: typeof AppProjectsKanbanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/gantt': {
      id: '/_app/projects/gantt'
      path: '/projects/gantt'
      fullPath: '/projects/gantt'
      preLoaderRoute: typeof AppProjectsGanttRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing/social': {
      id: '/_app/marketing/social'
      path: '/marketing/social'
      fullPath: '/marketing/social'
      preLoaderRoute: typeof AppMarketingSocialRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing/funnels': {
      id: '/_app/marketing/funnels'
      path: '/marketing/funnels'
      fullPath: '/marketing/funnels'
      preLoaderRoute: typeof AppMarketingFunnelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing/email': {
      id: '/_app/marketing/email'
      path: '/marketing/email'
      fullPath: '/marketing/email'
      preLoaderRoute: typeof AppMarketingEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing/campaigns': {
      id: '/_app/marketing/campaigns'
      path: '/marketing/campaigns'
      fullPath: '/marketing/campaigns'
      preLoaderRoute: typeof AppMarketingCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing/automation': {
      id: '/_app/marketing/automation'
      path: '/marketing/automation'
      fullPath: '/marketing/automation'
      preLoaderRoute: typeof AppMarketingAutomationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing/audience': {
      id: '/_app/marketing/audience'
      path: '/marketing/audience'
      fullPath: '/marketing/audience'
      preLoaderRoute: typeof AppMarketingAudienceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/marketing/analytics': {
      id: '/_app/marketing/analytics'
      path: '/marketing/analytics'
      fullPath: '/marketing/analytics'
      preLoaderRoute: typeof AppMarketingAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge-base/categories': {
      id: '/_app/knowledge-base/categories'
      path: '/knowledge-base/categories'
      fullPath: '/knowledge-base/categories'
      preLoaderRoute: typeof AppKnowledgeBaseCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/knowledge-base/articles': {
      id: '/_app/knowledge-base/articles'
      path: '/knowledge-base/articles'
      fullPath: '/knowledge-base/articles'
      preLoaderRoute: typeof AppKnowledgeBaseArticlesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/warehouses': {
      id: '/_app/inventory/warehouses'
      path: '/inventory/warehouses'
      fullPath: '/inventory/warehouses'
      preLoaderRoute: typeof AppInventoryWarehousesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/vendors': {
      id: '/_app/inventory/vendors'
      path: '/inventory/vendors'
      fullPath: '/inventory/vendors'
      preLoaderRoute: typeof AppInventoryVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/stock': {
      id: '/_app/inventory/stock'
      path: '/inventory/stock'
      fullPath: '/inventory/stock'
      preLoaderRoute: typeof AppInventoryStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/reports': {
      id: '/_app/inventory/reports'
      path: '/inventory/reports'
      fullPath: '/inventory/reports'
      preLoaderRoute: typeof AppInventoryReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/purchase-orders': {
      id: '/_app/inventory/purchase-orders'
      path: '/inventory/purchase-orders'
      fullPath: '/inventory/purchase-orders'
      preLoaderRoute: typeof AppInventoryPurchaseOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/products': {
      id: '/_app/inventory/products'
      path: '/inventory/products'
      fullPath: '/inventory/products'
      preLoaderRoute: typeof AppInventoryProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/categories': {
      id: '/_app/inventory/categories'
      path: '/inventory/categories'
      fullPath: '/inventory/categories'
      preLoaderRoute: typeof AppInventoryCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/assignments': {
      id: '/_app/inventory/assignments'
      path: '/inventory/assignments'
      fullPath: '/inventory/assignments'
      preLoaderRoute: typeof AppInventoryAssignmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/assets': {
      id: '/_app/inventory/assets'
      path: '/inventory/assets'
      fullPath: '/inventory/assets'
      preLoaderRoute: typeof AppInventoryAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hrms/settings': {
      id: '/_app/hrms/settings'
      path: '/hrms/settings'
      fullPath: '/hrms/settings'
      preLoaderRoute: typeof AppHrmsSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hrms/reports': {
      id: '/_app/hrms/reports'
      path: '/hrms/reports'
      fullPath: '/hrms/reports'
      preLoaderRoute: typeof AppHrmsReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hrms/performance': {
      id: '/_app/hrms/performance'
      path: '/hrms/performance'
      fullPath: '/hrms/performance'
      preLoaderRoute: typeof AppHrmsPerformanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hrms/payroll': {
      id: '/_app/hrms/payroll'
      path: '/hrms/payroll'
      fullPath: '/hrms/payroll'
      preLoaderRoute: typeof AppHrmsPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hrms/leave': {
      id: '/_app/hrms/leave'
      path: '/hrms/leave'
      fullPath: '/hrms/leave'
      preLoaderRoute: typeof AppHrmsLeaveRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hrms/employees': {
      id: '/_app/hrms/employees'
      path: '/hrms/employees'
      fullPath: '/hrms/employees'
      preLoaderRoute: typeof AppHrmsEmployeesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hrms/documents': {
      id: '/_app/hrms/documents'
      path: '/hrms/documents'
      fullPath: '/hrms/documents'
      preLoaderRoute: typeof AppHrmsDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hrms/departments': {
      id: '/_app/hrms/departments'
      path: '/hrms/departments'
      fullPath: '/hrms/departments'
      preLoaderRoute: typeof AppHrmsDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hrms/attendance': {
      id: '/_app/hrms/attendance'
      path: '/hrms/attendance'
      fullPath: '/hrms/attendance'
      preLoaderRoute: typeof AppHrmsAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/transactions': {
      id: '/_app/finance/transactions'
      path: '/finance/transactions'
      fullPath: '/finance/transactions'
      preLoaderRoute: typeof AppFinanceTransactionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/revenue': {
      id: '/_app/finance/revenue'
      path: '/finance/revenue'
      fullPath: '/finance/revenue'
      preLoaderRoute: typeof AppFinanceRevenueRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/payments': {
      id: '/_app/finance/payments'
      path: '/finance/payments'
      fullPath: '/finance/payments'
      preLoaderRoute: typeof AppFinancePaymentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/invoices': {
      id: '/_app/finance/invoices'
      path: '/finance/invoices'
      fullPath: '/finance/invoices'
      preLoaderRoute: typeof AppFinanceInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/expenses': {
      id: '/_app/finance/expenses'
      path: '/finance/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof AppFinanceExpensesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/cash-flow': {
      id: '/_app/finance/cash-flow'
      path: '/finance/cash-flow'
      fullPath: '/finance/cash-flow'
      preLoaderRoute: typeof AppFinanceCashFlowRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance/budgets': {
      id: '/_app/finance/budgets'
      path: '/finance/budgets'
      fullPath: '/finance/budgets'
      preLoaderRoute: typeof AppFinanceBudgetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/settings': {
      id: '/_app/crm/settings'
      path: '/crm/settings'
      fullPath: '/crm/settings'
      preLoaderRoute: typeof AppCrmSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/pipeline': {
      id: '/_app/crm/pipeline'
      path: '/crm/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof AppCrmPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/leads': {
      id: '/_app/crm/leads'
      path: '/crm/leads'
      fullPath: '/crm/leads'
      preLoaderRoute: typeof AppCrmLeadsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/inbox': {
      id: '/_app/crm/inbox'
      path: '/crm/inbox'
      fullPath: '/crm/inbox'
      preLoaderRoute: typeof AppCrmInboxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/email': {
      id: '/_app/crm/email'
      path: '/crm/email'
      fullPath: '/crm/email'
      preLoaderRoute: typeof AppCrmEmailRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/deals': {
      id: '/_app/crm/deals'
      path: '/crm/deals'
      fullPath: '/crm/deals'
      preLoaderRoute: typeof AppCrmDealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/customers': {
      id: '/_app/crm/customers'
      path: '/crm/customers'
      fullPath: '/crm/customers'
      preLoaderRoute: typeof AppCrmCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/calls': {
      id: '/_app/crm/calls'
      path: '/crm/calls'
      fullPath: '/crm/calls'
      preLoaderRoute: typeof AppCrmCallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/crm/activities': {
      id: '/_app/crm/activities'
      path: '/crm/activities'
      fullPath: '/crm/activities'
      preLoaderRoute: typeof AppCrmActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collaboration/messages': {
      id: '/_app/collaboration/messages'
      path: '/collaboration/messages'
      fullPath: '/collaboration/messages'
      preLoaderRoute: typeof AppCollaborationMessagesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collaboration/meetings': {
      id: '/_app/collaboration/meetings'
      path: '/collaboration/meetings'
      fullPath: '/collaboration/meetings'
      preLoaderRoute: typeof AppCollaborationMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collaboration/channels': {
      id: '/_app/collaboration/channels'
      path: '/collaboration/channels'
      fullPath: '/collaboration/channels'
      preLoaderRoute: typeof AppCollaborationChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/collaboration/calls': {
      id: '/_app/collaboration/calls'
      path: '/collaboration/calls'
      fullPath: '/collaboration/calls'
      preLoaderRoute: typeof AppCollaborationCallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation/workflows': {
      id: '/_app/automation/workflows'
      path: '/automation/workflows'
      fullPath: '/automation/workflows'
      preLoaderRoute: typeof AppAutomationWorkflowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation/triggers': {
      id: '/_app/automation/triggers'
      path: '/automation/triggers'
      fullPath: '/automation/triggers'
      preLoaderRoute: typeof AppAutomationTriggersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automation/logs': {
      id: '/_app/automation/logs'
      path: '/automation/logs'
      fullPath: '/automation/logs'
      preLoaderRoute: typeof AppAutomationLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-assistant/history': {
      id: '/_app/ai-assistant/history'
      path: '/ai-assistant/history'
      fullPath: '/ai-assistant/history'
      preLoaderRoute: typeof AppAiAssistantHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/tax': {
      id: '/_app/accounting/tax'
      path: '/accounting/tax'
      fullPath: '/accounting/tax'
      preLoaderRoute: typeof AppAccountingTaxRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/reports': {
      id: '/_app/accounting/reports'
      path: '/accounting/reports'
      fullPath: '/accounting/reports'
      preLoaderRoute: typeof AppAccountingReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/ledger': {
      id: '/_app/accounting/ledger'
      path: '/accounting/ledger'
      fullPath: '/accounting/ledger'
      preLoaderRoute: typeof AppAccountingLedgerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/accounting/journals': {
      id: '/_app/accounting/journals'
      path: '/accounting/journals'
      fullPath: '/accounting/journals'
      preLoaderRoute: typeof AppAccountingJournalsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAccountingJournalsRoute: typeof AppAccountingJournalsRoute
  AppAccountingLedgerRoute: typeof AppAccountingLedgerRoute
  AppAccountingReportsRoute: typeof AppAccountingReportsRoute
  AppAccountingTaxRoute: typeof AppAccountingTaxRoute
  AppAiAssistantHistoryRoute: typeof AppAiAssistantHistoryRoute
  AppAutomationLogsRoute: typeof AppAutomationLogsRoute
  AppAutomationTriggersRoute: typeof AppAutomationTriggersRoute
  AppAutomationWorkflowsRoute: typeof AppAutomationWorkflowsRoute
  AppCollaborationCallsRoute: typeof AppCollaborationCallsRoute
  AppCollaborationChannelsRoute: typeof AppCollaborationChannelsRoute
  AppCollaborationMeetingsRoute: typeof AppCollaborationMeetingsRoute
  AppCollaborationMessagesRoute: typeof AppCollaborationMessagesRoute
  AppCrmActivitiesRoute: typeof AppCrmActivitiesRoute
  AppCrmCallsRoute: typeof AppCrmCallsRoute
  AppCrmCustomersRoute: typeof AppCrmCustomersRoute
  AppCrmDealsRoute: typeof AppCrmDealsRoute
  AppCrmEmailRoute: typeof AppCrmEmailRoute
  AppCrmInboxRoute: typeof AppCrmInboxRoute
  AppCrmLeadsRoute: typeof AppCrmLeadsRoute
  AppCrmPipelineRoute: typeof AppCrmPipelineRoute
  AppCrmSettingsRoute: typeof AppCrmSettingsRoute
  AppFinanceBudgetsRoute: typeof AppFinanceBudgetsRoute
  AppFinanceCashFlowRoute: typeof AppFinanceCashFlowRoute
  AppFinanceExpensesRoute: typeof AppFinanceExpensesRoute
  AppFinanceInvoicesRoute: typeof AppFinanceInvoicesRoute
  AppFinancePaymentsRoute: typeof AppFinancePaymentsRoute
  AppFinanceRevenueRoute: typeof AppFinanceRevenueRoute
  AppFinanceTransactionsRoute: typeof AppFinanceTransactionsRoute
  AppHrmsAttendanceRoute: typeof AppHrmsAttendanceRoute
  AppHrmsDepartmentsRoute: typeof AppHrmsDepartmentsRoute
  AppHrmsDocumentsRoute: typeof AppHrmsDocumentsRoute
  AppHrmsEmployeesRoute: typeof AppHrmsEmployeesRoute
  AppHrmsLeaveRoute: typeof AppHrmsLeaveRoute
  AppHrmsPayrollRoute: typeof AppHrmsPayrollRoute
  AppHrmsPerformanceRoute: typeof AppHrmsPerformanceRoute
  AppHrmsReportsRoute: typeof AppHrmsReportsRoute
  AppHrmsSettingsRoute: typeof AppHrmsSettingsRoute
  AppInventoryAssetsRoute: typeof AppInventoryAssetsRoute
  AppInventoryAssignmentsRoute: typeof AppInventoryAssignmentsRoute
  AppInventoryCategoriesRoute: typeof AppInventoryCategoriesRoute
  AppInventoryProductsRoute: typeof AppInventoryProductsRoute
  AppInventoryPurchaseOrdersRoute: typeof AppInventoryPurchaseOrdersRoute
  AppInventoryReportsRoute: typeof AppInventoryReportsRoute
  AppInventoryStockRoute: typeof AppInventoryStockRoute
  AppInventoryVendorsRoute: typeof AppInventoryVendorsRoute
  AppInventoryWarehousesRoute: typeof AppInventoryWarehousesRoute
  AppKnowledgeBaseArticlesRoute: typeof AppKnowledgeBaseArticlesRoute
  AppKnowledgeBaseCategoriesRoute: typeof AppKnowledgeBaseCategoriesRoute
  AppMarketingAnalyticsRoute: typeof AppMarketingAnalyticsRoute
  AppMarketingAudienceRoute: typeof AppMarketingAudienceRoute
  AppMarketingAutomationRoute: typeof AppMarketingAutomationRoute
  AppMarketingCampaignsRoute: typeof AppMarketingCampaignsRoute
  AppMarketingEmailRoute: typeof AppMarketingEmailRoute
  AppMarketingFunnelsRoute: typeof AppMarketingFunnelsRoute
  AppMarketingSocialRoute: typeof AppMarketingSocialRoute
  AppProjectsGanttRoute: typeof AppProjectsGanttRoute
  AppProjectsKanbanRoute: typeof AppProjectsKanbanRoute
  AppProjectsListRoute: typeof AppProjectsListRoute
  AppProjectsMilestonesRoute: typeof AppProjectsMilestonesRoute
  AppRecruitmentAssessmentsRoute: typeof AppRecruitmentAssessmentsRoute
  AppRecruitmentCandidatesRoute: typeof AppRecruitmentCandidatesRoute
  AppRecruitmentInterviewsRoute: typeof AppRecruitmentInterviewsRoute
  AppRecruitmentJobsRoute: typeof AppRecruitmentJobsRoute
  AppRecruitmentOffersRoute: typeof AppRecruitmentOffersRoute
  AppRecruitmentOnboardingRoute: typeof AppRecruitmentOnboardingRoute
  AppRecruitmentReportsRoute: typeof AppRecruitmentReportsRoute
  AppRecruitmentRequisitionsRoute: typeof AppRecruitmentRequisitionsRoute
  AppRecruitmentSettingsRoute: typeof AppRecruitmentSettingsRoute
  AppReportsAnalyticsRoute: typeof AppReportsAnalyticsRoute
  AppReportsExportsRoute: typeof AppReportsExportsRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsIntegrationsRoute: typeof AppSettingsIntegrationsRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppTasksCalendarRoute: typeof AppTasksCalendarRoute
  AppTasksKanbanRoute: typeof AppTasksKanbanRoute
  AppTasksListRoute: typeof AppTasksListRoute
  AppTasksTimelineRoute: typeof AppTasksTimelineRoute
  AppAccountingIndexRoute: typeof AppAccountingIndexRoute
  AppAiAssistantIndexRoute: typeof AppAiAssistantIndexRoute
  AppAutomationIndexRoute: typeof AppAutomationIndexRoute
  AppCollaborationIndexRoute: typeof AppCollaborationIndexRoute
  AppCrmIndexRoute: typeof AppCrmIndexRoute
  AppFinanceIndexRoute: typeof AppFinanceIndexRoute
  AppHrmsIndexRoute: typeof AppHrmsIndexRoute
  AppInventoryIndexRoute: typeof AppInventoryIndexRoute
  AppKnowledgeBaseIndexRoute: typeof AppKnowledgeBaseIndexRoute
  AppMarketingIndexRoute: typeof AppMarketingIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppRecruitmentIndexRoute: typeof AppRecruitmentIndexRoute
  AppReportsIndexRoute: typeof AppReportsIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppTasksIndexRoute: typeof AppTasksIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAccountingJournalsRoute: AppAccountingJournalsRoute,
  AppAccountingLedgerRoute: AppAccountingLedgerRoute,
  AppAccountingReportsRoute: AppAccountingReportsRoute,
  AppAccountingTaxRoute: AppAccountingTaxRoute,
  AppAiAssistantHistoryRoute: AppAiAssistantHistoryRoute,
  AppAutomationLogsRoute: AppAutomationLogsRoute,
  AppAutomationTriggersRoute: AppAutomationTriggersRoute,
  AppAutomationWorkflowsRoute: AppAutomationWorkflowsRoute,
  AppCollaborationCallsRoute: AppCollaborationCallsRoute,
  AppCollaborationChannelsRoute: AppCollaborationChannelsRoute,
  AppCollaborationMeetingsRoute: AppCollaborationMeetingsRoute,
  AppCollaborationMessagesRoute: AppCollaborationMessagesRoute,
  AppCrmActivitiesRoute: AppCrmActivitiesRoute,
  AppCrmCallsRoute: AppCrmCallsRoute,
  AppCrmCustomersRoute: AppCrmCustomersRoute,
  AppCrmDealsRoute: AppCrmDealsRoute,
  AppCrmEmailRoute: AppCrmEmailRoute,
  AppCrmInboxRoute: AppCrmInboxRoute,
  AppCrmLeadsRoute: AppCrmLeadsRoute,
  AppCrmPipelineRoute: AppCrmPipelineRoute,
  AppCrmSettingsRoute: AppCrmSettingsRoute,
  AppFinanceBudgetsRoute: AppFinanceBudgetsRoute,
  AppFinanceCashFlowRoute: AppFinanceCashFlowRoute,
  AppFinanceExpensesRoute: AppFinanceExpensesRoute,
  AppFinanceInvoicesRoute: AppFinanceInvoicesRoute,
  AppFinancePaymentsRoute: AppFinancePaymentsRoute,
  AppFinanceRevenueRoute: AppFinanceRevenueRoute,
  AppFinanceTransactionsRoute: AppFinanceTransactionsRoute,
  AppHrmsAttendanceRoute: AppHrmsAttendanceRoute,
  AppHrmsDepartmentsRoute: AppHrmsDepartmentsRoute,
  AppHrmsDocumentsRoute: AppHrmsDocumentsRoute,
  AppHrmsEmployeesRoute: AppHrmsEmployeesRoute,
  AppHrmsLeaveRoute: AppHrmsLeaveRoute,
  AppHrmsPayrollRoute: AppHrmsPayrollRoute,
  AppHrmsPerformanceRoute: AppHrmsPerformanceRoute,
  AppHrmsReportsRoute: AppHrmsReportsRoute,
  AppHrmsSettingsRoute: AppHrmsSettingsRoute,
  AppInventoryAssetsRoute: AppInventoryAssetsRoute,
  AppInventoryAssignmentsRoute: AppInventoryAssignmentsRoute,
  AppInventoryCategoriesRoute: AppInventoryCategoriesRoute,
  AppInventoryProductsRoute: AppInventoryProductsRoute,
  AppInventoryPurchaseOrdersRoute: AppInventoryPurchaseOrdersRoute,
  AppInventoryReportsRoute: AppInventoryReportsRoute,
  AppInventoryStockRoute: AppInventoryStockRoute,
  AppInventoryVendorsRoute: AppInventoryVendorsRoute,
  AppInventoryWarehousesRoute: AppInventoryWarehousesRoute,
  AppKnowledgeBaseArticlesRoute: AppKnowledgeBaseArticlesRoute,
  AppKnowledgeBaseCategoriesRoute: AppKnowledgeBaseCategoriesRoute,
  AppMarketingAnalyticsRoute: AppMarketingAnalyticsRoute,
  AppMarketingAudienceRoute: AppMarketingAudienceRoute,
  AppMarketingAutomationRoute: AppMarketingAutomationRoute,
  AppMarketingCampaignsRoute: AppMarketingCampaignsRoute,
  AppMarketingEmailRoute: AppMarketingEmailRoute,
  AppMarketingFunnelsRoute: AppMarketingFunnelsRoute,
  AppMarketingSocialRoute: AppMarketingSocialRoute,
  AppProjectsGanttRoute: AppProjectsGanttRoute,
  AppProjectsKanbanRoute: AppProjectsKanbanRoute,
  AppProjectsListRoute: AppProjectsListRoute,
  AppProjectsMilestonesRoute: AppProjectsMilestonesRoute,
  AppRecruitmentAssessmentsRoute: AppRecruitmentAssessmentsRoute,
  AppRecruitmentCandidatesRoute: AppRecruitmentCandidatesRoute,
  AppRecruitmentInterviewsRoute: AppRecruitmentInterviewsRoute,
  AppRecruitmentJobsRoute: AppRecruitmentJobsRoute,
  AppRecruitmentOffersRoute: AppRecruitmentOffersRoute,
  AppRecruitmentOnboardingRoute: AppRecruitmentOnboardingRoute,
  AppRecruitmentReportsRoute: AppRecruitmentReportsRoute,
  AppRecruitmentRequisitionsRoute: AppRecruitmentRequisitionsRoute,
  AppRecruitmentSettingsRoute: AppRecruitmentSettingsRoute,
  AppReportsAnalyticsRoute: AppReportsAnalyticsRoute,
  AppReportsExportsRoute: AppReportsExportsRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsIntegrationsRoute: AppSettingsIntegrationsRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppTasksCalendarRoute: AppTasksCalendarRoute,
  AppTasksKanbanRoute: AppTasksKanbanRoute,
  AppTasksListRoute: AppTasksListRoute,
  AppTasksTimelineRoute: AppTasksTimelineRoute,
  AppAccountingIndexRoute: AppAccountingIndexRoute,
  AppAiAssistantIndexRoute: AppAiAssistantIndexRoute,
  AppAutomationIndexRoute: AppAutomationIndexRoute,
  AppCollaborationIndexRoute: AppCollaborationIndexRoute,
  AppCrmIndexRoute: AppCrmIndexRoute,
  AppFinanceIndexRoute: AppFinanceIndexRoute,
  AppHrmsIndexRoute: AppHrmsIndexRoute,
  AppInventoryIndexRoute: AppInventoryIndexRoute,
  AppKnowledgeBaseIndexRoute: AppKnowledgeBaseIndexRoute,
  AppMarketingIndexRoute: AppMarketingIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppRecruitmentIndexRoute: AppRecruitmentIndexRoute,
  AppReportsIndexRoute: AppReportsIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppTasksIndexRoute: AppTasksIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
